FROM almalinux:8
RUN yum install nginx -y
CMD ["nginx","-g","daemon off;"] # nginx runing command inside container
# nginx = nginx webserver
# -g = gobal configuration
# daemon off = forgrond,background process